//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalDataTask.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalDataTask.Application.Resources.AppMessage", typeof(AppMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Já existe um cadastro com esta descrição..
        /// </summary>
        public static string Validation_AlreadyDescription {
            get {
                return ResourceManager.GetString("Validation.AlreadyDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Já existe uma descrição para outro Id..
        /// </summary>
        public static string Validation_AlreadyDescriptionOtherId {
            get {
                return ResourceManager.GetString("Validation.AlreadyDescriptionOtherId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado dados..
        /// </summary>
        public static string Validation_DataTaskNotFound {
            get {
                return ResourceManager.GetString("Validation.DataTaskNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi encontrado dados pelo Id..
        /// </summary>
        public static string Validation_DataTaskNotFoundById {
            get {
                return ResourceManager.GetString("Validation.DataTaskNotFoundById", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} é obrigatório..
        /// </summary>
        public static string Validation_Description {
            get {
                return ResourceManager.GetString("Validation.Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} é obrigatório..
        /// </summary>
        public static string Validation_Status {
            get {
                return ResourceManager.GetString("Validation.Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} é obrigatório..
        /// </summary>
        public static string Validation_ValidateDate {
            get {
                return ResourceManager.GetString("Validation.ValidateDate", resourceCulture);
            }
        }
    }
}
